### PR TITLE
Add support for format of "Keep a Changelog"

### PR DESCRIPTION
**Pull request by koppor**
[Keep a Changelog](http://keepachangelog.com/en/1.0.0/) is an initiative for consistent CHANGELOG.md formatting. It especially includes links to GitHub diffs.

Example Changelog: https://github.com/olivierlacan/keep-a-changelog/blob/master/CHANGELOG.md

This PR adds support for that format.

### CODE REVIEW

**Comment by koppor** [comment]
With the detection of the format of [Keep a Changelog](http://keepachangelog.com/en/1.0.0/), this PR **does not** does not address the example of #1 anymore. I would say that this is acceptable, because it should be easy to convert that concrete example to a format close to "Keep a Changelog".

<s>The result for the linked HISTORY.md is

```
> Mar 28, 2016

* [#76] - Fix errors in exit handlers called via `onmount.teardown()`.

[v1.2.1]: https://github.com/rstacruz/onmount/compare/v1.2.0...v1.2.1
```

The spurious markdown link is because the linked HISTORY.md does not put all links to versions to the end of the file. Further, the linked file does not follow the convention to put links to issues es "embedded links" and not the end of the file.

</s>

**Comment by MoOx** [comment]
I use ``##`` all the times as second level title for my release, so not sure it's safe this way. I didn't touch this code for a while.
Here is an example https://github.com/phenomic/phenomic/blob/0.x/CHANGELOG.md#0210---2017-04-01

Do you think your change won't break anything?
Sorry I didn't write any tests haha

**Comment by koppor** [comment]
The good thing is that your `##` headings are not links:


grafik

The code checks for links at level 2:

grafik

So, the patch should just add support and break nothing ^^

**Comment by MoOx** [comment]
Should not break nothing for me. But what about some others that might have links?
Can't we find a better way to detect the format before parsing?
Eg:
- detect that we have `# Changelog`
- detect that `## [` have semver number after?

**Comment by koppor** [comment]
OK, I included a check for the format of "KeepAChangelog" (`# Changelog` at the first line and a line containing a secon-level-heading with a link having the version as link text).

As a consequence, second-level headings are only regarded if the format is approximately the format of "KeepAChangelog". The edge cases where users use `#Changelog` and `## [1.3.0]`, but do something strange such as `### [1.3.1]` should be very rare and thus are not treated in the check.

I also added `trim()` of the body to ensure that no newlines appear at the beginning or the end of the body.

**Comment by koppor** [comment]
I successfully released [version 1.1.1 of MADR](https://github.com/adr/madr/releases/tag/1.1.1) using this patch on Windows 10. So the PR is finally 😇 good to go from my side!

**Review by MoOx — APPROVED** [review]

**Comment by MoOx** [comment]
LGTM, thanks for this work!

**Pull request merged**
