### PR TITLE
Add command line option to change the change file name

### LINKED ISSUE #4: Ability to change default file name
I’d like to submit a PR for this but I want to discuss it first. How do you like to pass options? CLI argument, environment variables or something else?

### PR DESCRIPTION
**Pull request by sapegin**
Fix #4.

### CODE REVIEW

**Comment by sapegin** [comment]
@MoOx ping ;-)

**Comment by MoOx** [comment]
Oh nice. Sorry.
What about something even better: automatically looks for
- CHANGELOG.md
- Changelog.md
- changelog.md
- CHANGES.md
- changes.md
- Changes.md
- HISTORY.md
- History.md
- history.md
  ?

**Comment by MoOx** [comment]
Anyway, your work is good, I will merge and release soon.

**Comment by sapegin** [comment]
Good idea also!

**Pull request merged**
